# fly.toml file generated for shy-firefly-6436 on 2022-12-03T15:39:33+02:00

app = "shy-firefly-6436"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.script_checks]]
    command       = "/app/src/health_check.sh"
    args          = []
    grace_period  = "10s"
    interval      = "10s"
    restart_limit = 0
    timeout       = "5s"

